### ISSUE TITLE
LEGO plugin for dnshome.de - how to integrate into certbot-dns-multi?

### ISSUE THREAD

**Issue by DFS-90** [alexzorin/certbot-dns-multi#1]
Hello,

thank you very much for this great project!

LEGO recently added a new [plugin for dnshome.de](https://github.com/go-acme/lego/pull/1821) I'd really love to use with the latest [Nginx proxy manager branch](https://github.com/NginxProxyManager/nginx-proxy-manager/pull/2402) via certbot-multi-dns ("DnsMulti").

What has to be done in order to integrate the new dnshome.de plugin into certbot-dns-multi?

Thanks in advance and best regards,
David

**Comment by alexzorin** [comment]
Hi,

This plugin follows along the tagged releases of `lego`: https://github.com/go-acme/lego/releases

Once a new release of lego is available, it'll be available in this plugin as well. The new provider will appear then.

**Comment by alexzorin** [comment]
4.9.10 is now out!
