### ISSUE TITLE
Gandi V5 requires old deprecated GANDIV5_API_KEY

### ISSUE THREAD

**Issue by madalinignisca** [alexzorin/certbot-dns-multi#10]
When I try to use it with gandiv5, it exits with error:

`gandi: some credentials information are missing: GANDIV5_API_KEY`

I set the current PAT token. A hint: https://go-acme.github.io/lego/dns/gandiv5/

We can't even generate old api keys now on Gandi, or maybe only some still can.

For `gandiv5` I expected to use `GANDIV5_PERSONAL_ACCESS_TOKEN`

**Comment by alexzorin** [comment]
I think you'll have to wait for lego 4.15 to be released: https://github.com/go-acme/lego/issues/2041.

**Comment by jandebleser** [comment]
This issue still exists in version 4.16.1

**Comment by alexzorin** [comment]
No, I think it's fixed. This works for me:

```
$ cat /etc/letsencrypt/dns-multi-gandi.ini 
dns_multi_provider = gandiv5
GANDIV5_PERSONAL_ACCESS_TOKEN=abcdefghijklmnopqrstuvwx
```

I'm going to close this issue.
