### ISSUE TITLE
[Question] Difference between certbot, this and lego

### ISSUE THREAD

**Issue by lonix1** [alexzorin/certbot-dns-multi#2]
Hi @alexzorin. I found this repo from a link on the certbot docs.

What is the difference between certbot, this and lego? I don't understand in which cases to use one of those.

**Comment by alexzorin** [comment]
Certbot is an ACME client (software you can use to obtain an SSL certificate from a provider like Let's Encrypt).

Lego is also an ACME client.

This extends Certbot so it can be used to obtain certificates using the [DNS Challenge](https://letsencrypt.org/docs/challenge-types/#dns-01-challenge), if your domain's DNS provider is one of the 100+ providers listed in the README. It's necessary to use the DNS challenge if you want a wildcard certificate or if you want to get a certificate for a server which is not exposed to the internet, for example.

So, how does this project relate to Lego? Simply put, it takes advantage of the DNS providers that Lego supports, and makes them available in Certbot as well. 

Hope that helps.

**Comment by alexzorin** [comment]
Yep
