### ISSUE TITLE
lego 4.12.0 pdns txt record bug

### ISSUE THREAD

**Issue by binsys** [alexzorin/certbot-dns-multi#3]
see https://github.com/go-acme/lego/pull/1929

maybe need upgrade lego to 4.12.1

**Comment by alexzorin** [comment]
Yep. I'll do it soon, I'm a bit unwell.

**Comment by alexzorin** [comment]
OK, the snap is updated, pypi package is published, and the Docker images will be available once the build finishes, hopefully within the hour.
