### ISSUE TITLE
`go mod vendor` throwing a lot of errors

### ISSUE THREAD

**Issue by osirisinferi** [alexzorin/certbot-dns-multi#6]
Hi,

While trying to update my [Gentoo ebuild for `certbot-dns-multi`](https://github.com/osirisinferi/third-party-certbot-plugins/tree/main/app-crypt/certbot-dns-multi) to the latest version, I noticed my previous workflow doesn't work any more.

Gentoo requires maintainers for Go ebuilds to [package the vendor directory along with the source of the package itself](https://wiki.gentoo.org/wiki/Writing_go_Ebuilds).

I used to use the recommended `go mod vendor` approach, but this gives me 47 (!) errors. I'll paste the first few lines as an example, the rest is pretty much the same:

```
osiris@erazer bridge $ go mod vendor | grep "missing go.sum entry for module"
github.com/alexzorin/certbot-dns-multi/certbot_dns_multi/_internal/bridge imports
	github.com/go-acme/lego/v4/providers/dns imports
	github.com/go-acme/lego/v4/providers/dns/azure imports
	github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns: missing go.sum entry for module providing package github.com/Azure/azure-sdk-for-go/profiles/latest/dns/mgmt/dns (imported by github.com/go-acme/lego/v4/providers/dns/azure); to add:
	go get github.com/go-acme/lego/v4/providers/dns/azure@v4.13.3
github.com/alexzorin/certbot-dns-multi/certbot_dns_multi/_internal/bridge imports
	github.com/go-acme/lego/v4/providers/dns imports
	github.com/go-acme/lego/v4/providers/dns/azure imports
	github.com/Azure/azure-sdk-for-go/profiles/latest/privatedns/mgmt/privatedns: missing go.sum entry for module providing package github.com/Azure/azure-sdk-for-go/profiles/latest/privatedns/mgmt/privatedns (imported by github.com/go-acme/lego/v4/providers/dns/azure); to add:
(...)
```

While the guide linked above also mentions the instructions for generating a "dependency tarball" (which seems to work), I'd rather use the "vendor tarball" as I used previously for efficiency reasons: the vendor tarballs are less than 5&nbsp;MB while the dependency tarball is 224&nbsp;MB in size.

Now, it seems I can get `go mod vendor` to work when I do stuff like `go get`, but this modifies the `go.mod` and `go.sum` files, which obviously doesn't really fly if I'm using the original source files of `certbot-dns-multi` and would require patching the two files in my `ebuild`..

Is there anything I'm doing wrong or is there anything you can do from your end?

**Comment by alexzorin** [comment]
It looks like i just had to run `go mod tidy`. It's fixed in the main branch now.

**Comment by osirisinferi** [comment]
Ok, great, I'll wait until the next release of `lego`/`certbot-dns-multi` to add it to the Gentoo overlay :slightly_smiling_face:
